Repository honestbank/terraform-gcp-bigquery, pull requests merged in 2022-07, with the labels that each got.

#8 fix: support table expiration
  examples/create_dataset/main.tf
  modules/gcp_bigquery_volatile_dataset/README.md
  modules/gcp_bigquery_volatile_dataset/inputs.tf
  modules/gcp_bigquery_volatile_dataset/main.tf
  modules/gcp_bigquery_volatile_dataset/outputs.tf
Labels: size/L

#10 feat: add catalog info
  catalog-info.yaml
Labels: size/S

#12 fix: update service catalog type
  .github/workflows/checkov.yml
  .github/workflows/shiftleft-terraform.yaml
  .github/workflows/shiftleft-terraform.yml
  .github/workflows/terraform.yaml
  .github/workflows/terratest.yaml
  .pre-commit-config.yaml
  catalog-info.yaml
Labels: size/M

#13 fix: add missing materialized_view block
  modules/gcp_bigquery_materialized_view/inputs.tf
  modules/gcp_bigquery_materialized_view/main.tf
Labels: size/S
